# 单 server 版本
server:
  port: 8761
eureka:
  client:
    # 是否要注册到其他Eureka Server实例   默认true
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据   默认true
    fetch-registry: false
    service-url:
     defaultZone: http://user:misaki@localhost:8761/eureka/
spring:
  security:
    user:
      password: misaki